//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarDeLaHess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int id_address { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Numéro")]
        public string number { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Libellé")]
        public string title { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Ville")]
        public string city { get; set; }

        [Required]
        [Display(Name = "Code Postal")]
        public int postcode { get; set; }

        [Required]
        [Display(Name = "Pays")]
        public string country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
