//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarDeLaHess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id_item { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool available { get; set; }
        public float price { get; set; }
        public string picture { get; set; }
    }
}
