//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazarDeLaHess.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_user { get; set; }
        public Nullable<int> id_address { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Nom")]
        public string first_name { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        [Required]
        [Display(Name = "Prénom")]
        public string last_name { get; set; }

        [EmailAddress]
        [Required]
        [Display(Name = "email")]
        public string email { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string pass_word { get; set; }

        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
